layout_spectrum: 0.5896057
typography_spectrum: 0.4856631
color:
  saturation: 0.2825477
  lightness: 0.4742567
  brandStrength: 0.4946237
  brandColors:
    - '#F7F6F1'
    - '#816750'
    - '#51311C'
    - '#A8A095'
    - '#CFCCC7'
  rhythmicContrast: 0.4546243
name: Aalbalushi
